/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverlaysRouteImport } from './routes/overlays'
import { Route as SelectionRouteImport } from './routes/selection'
import { Route as SurfacesRouteImport } from './routes/surfaces'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysRoute = OverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionRoute = SelectionRouteImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SurfacesRoute = SurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overlays': typeof OverlaysRoute
  '/selection': typeof SelectionRoute
  '/surfaces': typeof SurfacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overlays': typeof OverlaysRoute
  '/selection': typeof SelectionRoute
  '/surfaces': typeof SurfacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overlays': typeof OverlaysRoute
  '/selection': typeof SelectionRoute
  '/surfaces': typeof SurfacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/overlays' | '/selection' | '/surfaces'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/overlays' | '/selection' | '/surfaces'
  id: '__root__' | '/' | '/overlays' | '/selection' | '/surfaces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverlaysRoute: typeof OverlaysRoute
  SelectionRoute: typeof SelectionRoute
  SurfacesRoute: typeof SurfacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays': {
      id: '/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof OverlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection': {
      id: '/selection'
      path: '/selection'
      fullPath: '/selection'
      preLoaderRoute: typeof SelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surfaces': {
      id: '/surfaces'
      path: '/surfaces'
      fullPath: '/surfaces'
      preLoaderRoute: typeof SurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverlaysRoute: OverlaysRoute,
  SelectionRoute: SelectionRoute,
  SurfacesRoute: SurfacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
